In [ ]:
#1. One Hot Encoding(OHE) - Binary value, Nominal data
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

#Create a column
df1=pd.DataFrame({"animal":["Cat","Dog","Camel","Dog","Dog","Camel","Cat"]})
df1

  animal
0    Cat
1    Dog
2  Camel
3    Dog
4    Dog
5  Camel
6    Cat

In [ ]:
#Apply OHE to endode the data
#Create OHE object
ohe=OneHotEncoder()

#Encode the animal column
animal_encoded=ohe.fit_transform(df1[["animal"]])
animal_encoded

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 7 stored elements and shape (7, 3)>

In [ ]:
#Convert the dataset into Data frame
animal_encoded_df=pd.DataFrame(animal_encoded.toarray(),columns=ohe.get_feature_names_out())
animal_encoded_df

   animal_Camel  animal_Cat  animal_Dog
0           0.0         1.0         0.0
1           0.0         0.0         1.0
2           1.0         0.0         0.0
3           0.0         0.0         1.0
4           0.0         0.0         1.0
5           1.0         0.0         0.0
6           0.0         1.0         0.0

In [ ]:
#2. Label encoding - It assigns numerical values to unique data in a column starting from 0,1,2... and so on
df2=pd.DataFrame({"name":["Rahul","Sanjib","Sachin","Subhashree"],
                  "gender":["Male","Male","Male","Female"],
                  "address":["West Bengsl","West Bengal","Bihar","Odisha"]})
df2

         name  gender      address
0       Rahul    Male  West Bengsl
1      Sanjib    Male  West Bengal
2      Sachin    Male        Bihar
3  Subhashree  Female       Odisha

In [ ]:
#Import label encoder
from sklearn.preprocessing import LabelEncoder
#Create object for Label Encoder
le=LabelEncoder()
le

LabelEncoder()

In [ ]:
#Encode the column gender and address
df2["gender_encoded"]=le.fit_transform(df2["gender"])
df2["address"]=le.fit_transform(df2["address"])
df2

         name  gender  address  gender_encoded
0       Rahul    Male        3               1
1      Sanjib    Male        2               1
2      Sachin    Male        0               1
3  Subhashree  Female        1               0

In [ ]:
#Ordinal Encoding - It is used for ordinal data
data = {
    "Customer": ["Amit", "Riya", "John", "Sara", "Neha"],
    "Review": ["Good", "Excellent","Average", "Poor", "Good"],
    "Size": ["Medium", "Large", "Small", "Large", "Medium"]
}

df3= pd.DataFrame(data)

print("Original DataFrame:")
print(df3)

Original DataFrame:
  Customer     Review    Size
0     Amit       Good  Medium
1     Riya  Excellent   Large
2     John    Average   Small
3     Sara       Poor   Large
4     Neha       Good  Medium

In [ ]:
#Import ordinal encoder
from sklearn.preprocessing import OrdinalEncoder

#Define the order of preference in descending order
categories=[
    ["Poor","Average","Good","Excellent"],
    ["Small","Medium","Large"]
]

#Create the ordinal encoder object
oe=OrdinalEncoder(categories=categories)
oe

OrdinalEncoder(categories=[['Poor', 'Average', 'Good', 'Excellent'],
                           ['Small', 'Medium', 'Large']])

In [ ]:
#Encode the column Review and Size
df3[["review_encoded","size_encoded"]]=oe.fit_transform(df3[["Review","Size"]])
df3

  Customer     Review    Size  review_encoded  size_encoded
0     Amit       Good  Medium             2.0           1.0
1     Riya  Excellent   Large             3.0           2.0
2     John    Average   Small             1.0           0.0
3     Sara       Poor   Large             0.0           2.0
4     Neha       Good  Medium             2.0           1.0

In [ ]:
#4. Frequency Encoding - While encoding the count of categoriocal data is used for encoding purpose
#Since we are using the count of data for encoding, hence it is also known as count encoding
data = {
    "Customer": ["Amit", "Riya", "John", "Sara", "Neha", "Raj"],
    "City": ["Delhi", "Mumbai", "Delhi", "Kolkata", "Mumbai", "Delhi"],
    "Product": ["Laptop", "Mobile", "Laptop", "Tablet", "Mobile", "Laptop"]
}

df4 = pd.DataFrame(data)

print("Original DataFrame:")
print(df4)

Original DataFrame:
  Customer     City Product
0     Amit    Delhi  Laptop
1     Riya   Mumbai  Mobile
2     John    Delhi  Laptop
3     Sara  Kolkata  Tablet
4     Neha   Mumbai  Mobile
5      Raj    Delhi  Laptop

In [ ]:
df4["city_encoded"]=df4["City"].map(df4["City"].value_counts())
df4["product_encoded"]=df4["Product"].map(df4["Product"].value_counts())
df4

  Customer     City Product  city_encoded  product_encoded
0     Amit    Delhi  Laptop             3                3
1     Riya   Mumbai  Mobile             2                2
2     John    Delhi  Laptop             3                3
3     Sara  Kolkata  Tablet             1                1
4     Neha   Mumbai  Mobile             2                2
5      Raj    Delhi  Laptop             3                3