In [ ]:
#1. One Hot Encoding(OHE) - Binary value, Nominal data
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

#Create a column
df1=pd.DataFrame({"animal":["Cat","Dog","Camel","Dog","Dog","Camel","Cat"]})
df1

  animal
0    Cat
1    Dog
2  Camel
3    Dog
4    Dog
5  Camel
6    Cat

In [ ]:
#Apply OHE to endode the data
#Create OHE object
ohe=OneHotEncoder()

#Encode the animal column
animal_encoded=ohe.fit_transform(df1[["animal"]])
animal_encoded

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 7 stored elements and shape (7, 3)>

In [ ]:
#Convert the dataset into Data frame
animal_encoded_df=pd.DataFrame(animal_encoded.toarray(),columns=ohe.get_feature_names_out())
animal_encoded_df

   animal_Camel  animal_Cat  animal_Dog
0           0.0         1.0         0.0
1           0.0         0.0         1.0
2           1.0         0.0         0.0
3           0.0         0.0         1.0
4           0.0         0.0         1.0
5           1.0         0.0         0.0
6           0.0         1.0         0.0

In [ ]:
#2. Label encoding - It assigns numerical values to unique data in a column starting from 0,1,2... and so on
df2=pd.DataFrame({"name":["Rahul","Sanjib","Sachin","Subhashree"],
                  "gender":["Male","Male","Male","Female"],
                  "address":["West Bengsl","West Bengal","Bihar","Odisha"]})
df2

         name  gender      address
0       Rahul    Male  West Bengsl
1      Sanjib    Male  West Bengal
2      Sachin    Male        Bihar
3  Subhashree  Female       Odisha

In [ ]:
#Import label encoder
from sklearn.preprocessing import LabelEncoder
#Create object for Label Encoder
le=LabelEncoder()
le

LabelEncoder()

In [ ]:
#Encode the column gender and address
df2["gender_encoded"]=le.fit_transform(df2["gender"])
df2["address"]=le.fit_transform(df2["address"])
df2

         name  gender  address  gender_encoded
0       Rahul    Male        3               1
1      Sanjib    Male        2               1
2      Sachin    Male        0               1
3  Subhashree  Female        1               0

In [ ]:
#Ordinal Encoding - It is used for ordinal data
data = {
    "Customer": ["Amit", "Riya", "John", "Sara", "Neha"],
    "Review": ["Good", "Excellent","Average", "Poor", "Good"],
    "Size": ["Medium", "Large", "Small", "Large", "Medium"]
}

df3= pd.DataFrame(data)

print("Original DataFrame:")
print(df3)

Original DataFrame:
  Customer     Review    Size
0     Amit       Good  Medium
1     Riya  Excellent   Large
2     John    Average   Small
3     Sara       Poor   Large
4     Neha       Good  Medium

In [ ]:
#Import ordinal encoder
from sklearn.preprocessing import OrdinalEncoder

#Define the order of preference in descending order
categories=[
    ["Poor","Average","Good","Excellent"],
    ["Small","Medium","Large"]
]

#Create the ordinal encoder object
oe=OrdinalEncoder(categories=categories)
oe

OrdinalEncoder(categories=[['Poor', 'Average', 'Good', 'Excellent'],
                           ['Small', 'Medium', 'Large']])

In [ ]:
#Encode the column Review and Size
df3[["review_encoded","size_encoded"]]=oe.fit_transform(df3[["Review","Size"]])
df3

  Customer     Review    Size  review_encoded  size_encoded
0     Amit       Good  Medium             2.0           1.0
1     Riya  Excellent   Large             3.0           2.0
2     John    Average   Small             1.0           0.0
3     Sara       Poor   Large             0.0           2.0
4     Neha       Good  Medium             2.0           1.0

In [ ]:
#4. Frequency Encoding - While encoding the count of categoriocal data is used for encoding purpose
#Since we are using the count of data for encoding, hence it is also known as count encoding
data = {
    "Customer": ["Amit", "Riya", "John", "Sara", "Neha", "Raj"],
    "City": ["Delhi", "Mumbai", "Delhi", "Kolkata", "Mumbai", "Delhi"],
    "Product": ["Laptop", "Mobile", "Laptop", "Tablet", "Mobile", "Laptop"]
}

df4 = pd.DataFrame(data)

print("Original DataFrame:")
print(df4)

Original DataFrame:
  Customer     City Product
0     Amit    Delhi  Laptop
1     Riya   Mumbai  Mobile
2     John    Delhi  Laptop
3     Sara  Kolkata  Tablet
4     Neha   Mumbai  Mobile
5      Raj    Delhi  Laptop

In [ ]:
df4["city_encoded"]=df4["City"].map(df4["City"].value_counts())
df4["product_encoded"]=df4["Product"].map(df4["Product"].value_counts())
df4

  Customer     City Product  city_encoded  product_encoded
0     Amit    Delhi  Laptop             3                3
1     Riya   Mumbai  Mobile             2                2
2     John    Delhi  Laptop             3                3
3     Sara  Kolkata  Tablet             1                1
4     Neha   Mumbai  Mobile             2                2
5      Raj    Delhi  Laptop             3                3

In [ ]:
#Scaling - It's scale all the feature on same scale
#Standardzation - We convert the data set in such a manner that the mean value becomes zero and SD becomes 1
import pandas as pd

df = pd.DataFrame({
    "Name": ["Amit", "Riya", "John", "Sara", "Neha"],
    "Age": [18, 22, 20, 25, 19],
    "salary": [50000, 90000, 75000, 95000, 60000],
    "Travel_time": [2, 8, 5, 10, 3]
})

df

   Name  Age  salary  Travel_time
0  Amit   18   50000            2
1  Riya   22   90000            8
2  John   20   75000            5
3  Sara   25   95000           10
4  Neha   19   60000            3

In [ ]:
#import standardscaler from sklearn
from sklearn.preprocessing import StandardScaler
#Create the object for StandardScaler
ss=StandardScaler()
ss

StandardScaler()

In [ ]:
scaled_data=ss.fit_transform(df[["Age","salary","Travel_time"]])
scaled_data    #Array form

array([[-1.12815215, -1.39970842, -1.19734219],
       [ 0.48349378,  0.93313895,  0.79822813],
       [-0.32232919,  0.05832118, -0.19955703],
       [ 1.69222822,  1.22474487,  1.46341823],
       [-0.72524067, -0.81649658, -0.86474714]])

In [ ]:
#Convert array to DataFrame
scaled_df=pd.DataFrame(scaled_data,columns=df[["Age","salary","Travel_time"]].columns)
scaled_df

        Age    salary  Travel_time
0 -1.128152 -1.399708    -1.197342
1  0.483494  0.933139     0.798228
2 -0.322329  0.058321    -0.199557
3  1.692228  1.224745     1.463418
4 -0.725241 -0.816497    -0.864747

                Age    salary   Travel_time
count  5.000000e+00  5.000000  5.000000e+00
mean  -3.108624e-16  0.000000  1.110223e-16
std    1.118034e+00  1.118034  1.118034e+00
min   -1.128152e+00 -1.399708 -1.197342e+00
25%   -7.252407e-01 -0.816497 -8.647471e-01
50%   -3.223292e-01  0.058321 -1.995570e-01
75%    4.834938e-01  0.933139  7.982281e-01
max    1.692228e+00  1.224745  1.463418e+00

In [ ]:
#Min-Max Scaler
from sklearn.preprocessing import MinMaxScaler
#Create the object
mm=MinMaxScaler()
mm

MinMaxScaler()

In [ ]:
scaled_data_2=mm.fit_transform(df[["Age","salary","Travel_time"]])
scaled_data_2

array([[0.        , 0.        , 0.        ],
       [0.57142857, 0.88888889, 0.75      ],
       [0.28571429, 0.55555556, 0.375     ],
       [1.        , 1.        , 1.        ],
       [0.14285714, 0.22222222, 0.125     ]])

In [ ]:
df_scaled_2=pd.DataFrame(scaled_data_2,columns=df[["Age","salary","Travel_time"]].columns)
df_scaled_2

        Age    salary  Travel_time
0  0.000000  0.000000        0.000
1  0.571429  0.888889        0.750
2  0.285714  0.555556        0.375
3  1.000000  1.000000        1.000
4  0.142857  0.222222        0.125

In [ ]:
from sklearn.preprocessing import Normalizer
#Create the object
nm=Normalizer()
nm

Normalizer()

In [ ]:
scaled_data_2=nm.fit_transform(df[["Age","salary","Travel_time"]])
scaled_data_2

array([[3.59999976e-04, 9.99999934e-01, 3.99999974e-05],
       [2.44444436e-04, 9.99999966e-01, 8.88888859e-05],
       [2.66666657e-04, 9.99999962e-01, 6.66666641e-05],
       [2.63157884e-04, 9.99999960e-01, 1.05263154e-04],
       [3.16666650e-04, 9.99999949e-01, 4.99999974e-05]])

In [ ]:
df_scaled_3=pd.DataFrame(scaled_data_2,columns=df[["Age","salary","Travel_time"]].columns)
df_scaled_3

        Age  salary  Travel_time
0  0.000360     1.0     0.000040
1  0.000244     1.0     0.000089
2  0.000267     1.0     0.000067
3  0.000263     1.0     0.000105
4  0.000317     1.0     0.000050

In [ ]:
from sklearn.preprocessing import RobustScaler
#Create the object
rb=RobustScaler()
rb

RobustScaler()

In [ ]:
scaled_data_4=rb.fit_transform(df[["Age","salary","Travel_time"]])
scaled_data_4

array([[-0.66666667, -0.83333333, -0.6       ],
       [ 0.66666667,  0.5       ,  0.6       ],
       [ 0.        ,  0.        ,  0.        ],
       [ 1.66666667,  0.66666667,  1.        ],
       [-0.33333333, -0.5       , -0.4       ]])

In [ ]:
#Convert the scaled data to dataframe
df_scaled_4=pd.DataFrame(scaled_data_4,columns=df[["Age","salary","Travel_time"]].columns)
df_scaled_4

        Age    salary  Travel_time
0 -0.666667 -0.833333         -0.6
1  0.666667  0.500000          0.6
2  0.000000  0.000000          0.0
3  1.666667  0.666667          1.0
4 -0.333333 -0.500000         -0.4

In [ ]:
#Outlier capping - Instead of removing the outlier we can cap the outlier value within the data range
#IQR = Q3-Q1
#upper_fence=Q3+1.5*IQR
#lower_fence=Q1-1.5*IQR

import pandas as pd
data={
    "Name":["Priyanka","Sudeep","Sujoy","Anuska"],
    "Salary":[30000,28000,32000,6768778778778]      #salary contains the outliers
}

df6=pd.DataFrame(data)
df6

       Name         Salary
0  Priyanka          30000
1    Sudeep          28000
2     Sujoy          32000
3    Anuska  6768778778778

In [ ]:
import numpy as np
Q1=np.percentile(df6["Salary"],25)
Q3=np.percentile(df6["Salary"],75)
IQR=Q3-Q1
upper_fence=Q3+1.5*IQR
lower_fence=Q1-1.5*IQR
print(Q1,Q3,IQR,upper_fence,lower_fence)

29500.0 1692194718694.5 1692194689194.5 4230486752486.25 -2538292004291.75

In [ ]:
#cap the salary
df6["Salary"]=np.where(df6["Salary"]>upper_fence,upper_fence,df6["Salary"])
df6["Salary"]=np.where(df6["Salary"]<lower_fence,lower_fence,df6["Salary"])
df6

       Name        Salary
0  Priyanka  3.000000e+04
1    Sudeep  2.800000e+04
2     Sujoy  3.200000e+04
3    Anuska  4.230487e+12

In [ ]:
df6["Salary_cap"]=np.clip(df6["Salary"],lower_fence,upper_fence)
df6

       Name        Salary    Salary_cap
0  Priyanka  3.000000e+04  3.000000e+04
1    Sudeep  2.800000e+04  2.800000e+04
2     Sujoy  3.200000e+04  3.200000e+04
3    Anuska  4.230487e+12  4.230487e+12