In [ ]:
#Extract hour from the column "Dep_Time" and create a new column based on the following conditions
#Dep_hour 0 to 4 ---> Late Night , 4-8 ----->Early Morning,  8-12 ----->Morning,  12-4 ----> Afternoon, 4-8 ---->Evening, 8-0 ----> Night
#Most Expensive Route
#Find Top 5 Airlines with Highest Average Ticket Price.

In [23]:
import pandas as pd

In [12]:
#Load the data
flight=pd.read_excel("/Users/cashify/Desktop/flight_price (1).xlsx")
flight

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [30]:
#Change the Object to Datetime
flight["Dep_Time"]=pd. to_datetime(flight["Dep_Time"])
print(flight["Dep_Time"].dtype)

datetime64[ns]

In [39]:
# Step 1: Extract hour (already converted above)
flight["Dep_Hour"]=flight["Dep_Time"].dt.hour
print(flight["Dep_Hour"].head(10))

0    22
1     5
2     9
3    18
4    16
5     9
6    18
7     8
8     8
9    11
Name: Dep_Hour, dtype: int32

In [40]:
#Step 2: Categorize Time Periods
def get_time_period(hour):
    if 0 <= hour < 4:
        return 'Late Night'
    elif 4 <= hour < 8:    
        return 'Early Morning'
    elif 8 <= hour < 12:
        return 'Morning'
    elif 12 <= hour < 16:
        return 'Afternoon'
    elif 16 <= hour < 20:
        return 'Evening'
    else:
        return 'Night'

In [45]:
#Step 3: Apply udf to the Dataframe
flight["Time Period"] = flight["Dep_Hour"].apply(get_time_period)

In [52]:
# Most expensive routes
flight.groupby("Route")["Price"].agg(["mean","count","max","mean"])

                                     mean  count    max          mean
Route
BLR → AMD → DEL              11134.166667     18  18387  11134.166667
BLR → BBI → DEL              11486.000000      5  12704  11486.000000
BLR → BDQ → DEL              11550.500000      8  28097  11550.500000
BLR → BOM → AMD → DEL        14751.600000      5  17345  14751.600000
BLR → BOM → BHO → DEL        17211.545455     11  26743  17211.545455
...                                   ...    ...    ...           ...
DEL → PNQ → COK               6602.071429     42  11378   6602.071429
DEL → RPR → NAG → BOM → COK  10891.411765     17  15586  10891.411765
DEL → TRV → COK               7835.625000     16  12677   7835.625000
DEL → UDR → BOM → COK        13859.277778     18  20747  13859.277778
MAA → CCU                     4789.892388    381  19630   4789.892388

[128 rows x 4 columns]

In [67]:
#Find Top 5 Airlines with Highest Average Ticket Price.
flight.groupby("Airline")["Price"].agg(["mean","count","std"]).sort_values(ascending=False)

TypeError: DataFrame.sort_values() missing 1 required positional argument: 'by'