In [1]:
#Extract hour from the column "Dep_Time" and create a new column based on the following conditions

#Dep_hour 
#0 to 4 ---> Late Night
#4-8 ----->Early Morning
#8-12 ----->Morning
#12-4 ----> Afternoon
#4-8 ---->Evening
#8-0 ----> Night

#Most Expensive Route

#Find Top 5 Airlines with Highest Average Ticket Price.

In [2]:
import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings("ignore")

In [3]:
#Load the flight data
df = pd.read_excel('/Users/cashify/Desktop/flight_price (1).xlsx')
print(df['Dep_Time'].head())

0    22:20
1    05:50
2    09:25
3    18:05
4    16:50
Name: Dep_Time, dtype: object

In [4]:
#Extract hour from the column "Dep_Time" and create a new column
df['Dep_Hour']=pd. to_datetime(df['Dep_Time']).dt.hour

In [5]:
print(df[['Dep_Time', 'Dep_Hour']].dtypes)

Dep_Time    object
Dep_Hour     int32
dtype: object

In [6]:
print(df[['Dep_Time', 'Dep_Hour']].head())

  Dep_Time  Dep_Hour
0    22:20        22
1    05:50         5
2    09:25         9
3    18:05        18
4    16:50        16

In [7]:
#Dep_hour 
#0 to 4 ---> Late Night
#4-8 ----->Early Morning
#8-12 ----->Morning
#12-4 ----> Afternoon
#4-8 ---->Evening
#8-0 ----> Night

def get_time(hour):
    if 0 <= hour < 4:
        return 'Late Night'
    elif 4 <= hour < 8:
        return 'Early Morning'
    elif 8 <= hour < 12:   
        return 'Morning'
    elif 12 <= hour < 16:    
        return 'Afternoon'
    elif 16 <= hour < 20:
        return 'Evening'
    else:
        return'Night'

In [8]:
#apply() - To apply a UDF to the DataFrame
df["Time_Period"]=df["Dep_Hour"].apply(get_time)
df
df.head(10)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Dep_Hour,Time_Period
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,22,Night
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,5,Early Morning
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,Morning
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,18,Evening
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,16,Evening
5,SpiceJet,24/06/2019,Kolkata,Banglore,CCU → BLR,09:00,11:25,2h 25m,non-stop,No info,3873,9,Morning
6,Jet Airways,12/03/2019,Banglore,New Delhi,BLR → BOM → DEL,18:55,10:25 13 Mar,15h 30m,1 stop,In-flight meal not included,11087,18,Evening
7,Jet Airways,01/03/2019,Banglore,New Delhi,BLR → BOM → DEL,08:00,05:05 02 Mar,21h 5m,1 stop,No info,22270,8,Morning
8,Jet Airways,12/03/2019,Banglore,New Delhi,BLR → BOM → DEL,08:55,10:25 13 Mar,25h 30m,1 stop,In-flight meal not included,11087,8,Morning
9,Multiple carriers,27/05/2019,Delhi,Cochin,DEL → BOM → COK,11:25,19:15,7h 50m,1 stop,No info,8625,11,Morning

In [9]:
#Most Expensive Route
df.groupby(["Route","Airline"])["Price"].sum().sort_values(ascending=False).reset_index().head(10)

                   Route            Airline     Price
0        DEL → BOM → COK  Multiple carriers  11209730
1        CCU → BOM → BLR        Jet Airways  10832533
2        DEL → BOM → COK        Jet Airways  10790542
3        BLR → BOM → DEL        Jet Airways   5958894
4        CCU → DEL → BLR        Jet Airways   3676704
5  DEL → JAI → BOM → COK        Jet Airways   2594181
6              BLR → DEL        Jet Airways   2483273
7              BLR → DEL             IndiGo   2443515
8        DEL → BOM → COK             IndiGo   2375859
9  DEL → AMD → BOM → COK        Jet Airways   1948396

In [10]:
# Find the top 5 Airlines with Highest Average Ticket Price.

df.groupby("Airline")["Price"].mean().sort_values(ascending=False).reset_index()

                              Airline         Price
0                Jet Airways Business  58358.666667
1                         Jet Airways  11643.923357
2   Multiple carriers Premium economy  11418.846154
3                   Multiple carriers  10902.678094
4                           Air India   9611.210616
5             Vistara Premium economy   8962.333333
6                             Vistara   7796.348643
7                               GoAir   5861.056701
8                              IndiGo   5673.682903
9                            Air Asia   5590.260188
10                           SpiceJet   4338.284841
11                             Trujet   4140.000000